// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f19cdab1-9162-4ca8-900f-33c1f6c35b55",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_w9OW5zpkv",
    "aws_user_pools_web_client_id": "41fhj408jsdm082okno3q8lrtm"
};


export default awsmobile;
